menu_background           0 50 130 1.0
menu_background_detail    107 0 1 1.0
friendly_background       2 18 28 1.0
enemy_background          25 15 8 1.0
friendly_starfield        11 80 124 0.65
enemy_starfield           121 57 57 0.63
turret(notused)           111 65 37 1.0
general_building          174 198 175 1.0
advanced_building         174 198 175 1.0
shipyard                  205 190 163 1.0
fighters                  168 193 207 1.0
mainguy                   205 190 163 1.24
enemy_status              107 0 1 1.0
friendly_status           0 53 0 1.3
allied_status             0 50 130 1.0
explosion                 103 59 54 2.0
friendly_explosion        89 0 38 1.0
factory_detail            107 70 0 1.8
researchlab_detail        40 86 47 2.0
powergenerator_detail     70 81 30 3.1
powergenerator_coverage   11 80 124 1.0
timebomb_detail           111 65 37 2.0
missileturret_detail      163 193 205 1.2
exciterturret_detail      65 35 0 3.9
massdriverturret_detail   60 40 18 2.0
regenturret_detail        174 198 175 1.0
signalstation_detail      173 219 197 1.0
jumpgate_detail           0 50 130 1.0
fighteryard_detail        205 190 163 1.0
bomberyard_detail         205 190 163 1.0
fighter_detail            70 81 30 1.0
bomber_detail             65 35 0 1.0
aifighter_detail          111 65 37 1.0
aibomber_detail           107 0 1  1.0
airepairdood_detail       107 0 1 1.0
aibigfireturret_detail    107 0 1 1.0
aispreadfireturret_detail 107 0 1 1.0
redgroup                  228 0 33 1.0
greengroup                0 176 66 1.0
bluegroup                 0 33 176 1.0
friendlyfire              0 176 66 1.0
enemyfire                 228 0 33 1.0
alliedfire                0 66 176 1.0
cloak                     205 190 163 1.24
radar_tint                      40 86 47 0.3
radar_gridlines                 40 86 47 1.0
radar_signalstation_coverage    40 86 47 1.0
radar_enemy_status              107 0 1 1.8
radar_friendly_status           0 234 0 1.0
radar_allied_status             0 50 130 1.8
particles_friendly_exhaust    56 132 68 1.0
particles_enemy_exhaust       132 56 68 1.0
particles_allied_exhaust      56 68 132 1.0
particles_neutral_exhaust     255 246 230 0.67
particles_switch              255 246 230 1.0
particles_healing             174 198 175 1.0
particles_explosion1          107 0 1 2.0
particles_explosion2          130 110 0 1.0
particles_explosion3          255 255 255 1.0
particles_spark               0 210 255 1.0
healthbar                     0 53 0 4.0
batterybar                    107 0 1 2.0
alert1                        255 0 0 1.0
alert2                        255 255 0 1.0

