Gate 88 Player
irc.gamesurge.net 6667 #gate88
irc.us.gamesurge.net 6667 #gate88
irc.eu.gamesurge.net 6667 #gate88
Netfire.TX.US.GameSurge.Net 6667 #gate88
Burstfire.UK.EU.GameSurge.net 6667 #gate88
Kanzi.CA.US.GameSurge.Net 6667 #gate88
ClanShells.DE.EU.GameSurge.net 6667 #gate88
Prothid.CA.US.GameSurge.Net 6667 #gate88
Reflex.UK.EU.GameSurge.net 6667 #gate88
Slim.NY.US.GameSurge.Net 6667 #gate88
Tukikohta.FI.EU.GameSurge.Net 6667 #gate88
